/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.gov.es.cb.sdro.view;

import br.gov.es.cb.sdro.control.ControlMilitarAdapter;
import br.gov.es.cb.sdro.model.Militar;
import br.gov.es.cb.sdro.model.MilitarAdapter;
import br.gov.es.cb.sdro.model.Unidade;
import br.gov.es.cb.sdro.model.SafoPostoGraducao;
import br.gov.es.cb.sdro.util.MilitarDAO;
import br.gov.es.cb.sdro.util.SafoPostoGraduacaoDAO;
import br.gov.es.cb.sdro.util.UnidadesDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Heitor
 */
public class TelaUnidades extends javax.swing.JInternalFrame {
   
     // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abaAlteraExclui;
    private javax.swing.JButton bntCarregaMilSubcmt;
    private javax.swing.JButton btnCarregaMilCmt;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbMilCmt;
    private javax.swing.JComboBox cmbMilSubcmt;
    private javax.swing.JComboBox cmbPostogradCmt;
    private javax.swing.JComboBox cmbPostogradSubcmt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCadastroUnidade;
    private javax.swing.JLabel lblCmt;
    private javax.swing.JLabel lblMilitarCmt;
    private javax.swing.JLabel lblMilitarSubcmt;
    private javax.swing.JLabel lblNomeUnidade;
    private javax.swing.JLabel lblPostoGradCmt;
    private javax.swing.JLabel lblPostoGradSubcmt;
    private javax.swing.JLabel lblSubcmt;
    private javax.swing.JTable tblUnidades;
    private javax.swing.JTextField txtNomeUnidade;
    // End of variables declaration//GEN-END:variables

    private ControlMilitarAdapter controlMilitar;
    UnidadesDAO unidadeDao;
    MilitarAdapter miladap;
    private List<MilitarAdapter> listMilAdap = new ArrayList();
    DefaultTableModel modeloTable = new DefaultTableModel();
    DefaultListModel modelList = new DefaultListModel();
    Unidade unidadeSelecionada;
    private List<Unidade> listaUnidade;
    private List<SafoPostoGraducao> listaPG = new SafoPostoGraduacaoDAO().buscaSafoPostoGraducaos();
    private List<Militar> listaMil = new MilitarDAO().buscaMilitars();
    String opcao;
    /**
     * Creates new form Unidades
     */
    public TelaUnidades() {
        initComponents();
        this.setVisible(true);
        unidadeDao = new UnidadesDAO();
        miladap = new MilitarAdapter();
        btnExcluir.setVisible(false);
        opcao = "Selecione";
        //define o modelo da tabela utilizada para exibir as unidades
        modeloTable = (DefaultTableModel) tblUnidades.getModel();
        atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abaAlteraExclui = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUnidades = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblCadastroUnidade = new javax.swing.JLabel();
        lblNomeUnidade = new javax.swing.JLabel();
        txtNomeUnidade = new javax.swing.JTextField();
        lblCmt = new javax.swing.JLabel();
        cmbPostogradCmt = new javax.swing.JComboBox();
        lblPostoGradCmt = new javax.swing.JLabel();
        lblSubcmt = new javax.swing.JLabel();
        lblPostoGradSubcmt = new javax.swing.JLabel();
        cmbPostogradSubcmt = new javax.swing.JComboBox();
        lblMilitarCmt = new javax.swing.JLabel();
        lblMilitarSubcmt = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        cmbMilCmt = new javax.swing.JComboBox<>();
        btnCarregaMilCmt = new javax.swing.JButton();
        cmbMilSubcmt = new javax.swing.JComboBox();
        bntCarregaMilSubcmt = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Lista de Unidades");

        tblUnidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nome", "idComandante", "idSubcomandante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUnidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUnidadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUnidades);
        if (tblUnidades.getColumnModel().getColumnCount() > 0) {
            tblUnidades.getColumnModel().getColumn(0).setResizable(false);
            tblUnidades.getColumnModel().getColumn(0).setPreferredWidth(15);
            tblUnidades.getColumnModel().getColumn(1).setResizable(false);
            tblUnidades.getColumnModel().getColumn(2).setResizable(false);
            tblUnidades.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        abaAlteraExclui.addTab("Buscar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCadastroUnidade.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCadastroUnidade.setText("Cadastro de Unidades");
        jPanel2.add(lblCadastroUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        lblNomeUnidade.setText("Nome da Unidade");
        jPanel2.add(lblNomeUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 90, 90, -1));
        jPanel2.add(txtNomeUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 220, 30));

        lblCmt.setText("Comandante");
        jPanel2.add(lblCmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        cmbPostogradCmt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmbPostogradCmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 130, 30));

        lblPostoGradCmt.setText("Posto/Graduação");
        jPanel2.add(lblPostoGradCmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        lblSubcmt.setText("SubComandante");
        jPanel2.add(lblSubcmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lblPostoGradSubcmt.setText("Posto/Graduação");
        jPanel2.add(lblPostoGradSubcmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        cmbPostogradSubcmt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmbPostogradSubcmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 130, 30));

        lblMilitarCmt.setText("Militar");
        jPanel2.add(lblMilitarCmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        lblMilitarSubcmt.setText("Militar");
        jPanel2.add(lblMilitarSubcmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel2.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 80, 40));

        cmbMilCmt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmbMilCmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 220, 30));

        btnCarregaMilCmt.setText(">");
        btnCarregaMilCmt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarregaMilCmtMouseClicked(evt);
            }
        });
        jPanel2.add(btnCarregaMilCmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 40, 30));

        cmbMilSubcmt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmbMilSubcmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 220, 30));

        bntCarregaMilSubcmt.setText(">");
        bntCarregaMilSubcmt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntCarregaMilSubcmtMouseClicked(evt);
            }
        });
        jPanel2.add(bntCarregaMilSubcmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, 30));

        btnExcluir.setText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        jPanel2.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 80, 40));

        btnNovo.setText("Novo");
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        jPanel2.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 80, 40));

        abaAlteraExclui.addTab("Alterar/Excluir", jPanel2);

        getContentPane().add(abaAlteraExclui, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCarregaMilSubcmtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCarregaMilSubcmtMouseClicked
        cmbMilSubcmt.removeAllItems();
        if (!cmbPostogradSubcmt.getSelectedItem().equals(opcao)) {
            listMilAdap = controlMilitar.getMilitarByPostoGraduacao(cmbPostogradSubcmt.getSelectedIndex());
            for (MilitarAdapter mil : listMilAdap) {
                cmbMilSubcmt.addItem(mil.getIdmilitar() + "");
            }
        }
    }//GEN-LAST:event_bntCarregaMilSubcmtMouseClicked

    private void btnCarregaMilCmtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarregaMilCmtMouseClicked
        cmbMilCmt.removeAllItems();
        if (!cmbPostogradCmt.getSelectedItem().equals(opcao)) {
            listMilAdap = controlMilitar.getMilitarByPostoGraduacao(cmbPostogradCmt.getSelectedIndex());
            for (MilitarAdapter mil : listMilAdap) {
                cmbMilCmt.addItem(mil.getIdmilitar() + "");
            }
        }
    }//GEN-LAST:event_btnCarregaMilCmtMouseClicked

    private void tblUnidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUnidadesMouseClicked
        //captura a linha selecionada para a tela de cadastro
        abaAlteraExclui.setSelectedIndex(1);
        unidadeSelecionada = listaUnidade.get(tblUnidades.getSelectedRow());
        txtNomeUnidade.setText(unidadeSelecionada.getNome());
        cmbPostogradCmt.setSelectedIndex(controlMilitar.getMilitarbyId(unidadeSelecionada.getIdcomandante()).getPostoGraduacao());
        cmbPostogradSubcmt.setSelectedIndex(controlMilitar.getMilitarbyId(unidadeSelecionada.getIdsubcomandante()).getPostoGraduacao());
        limpaCamposMilitar();
        cmbMilCmt.addItem(controlMilitar.getMilitarbyId(unidadeSelecionada.getIdcomandante()).getNome());
        cmbMilSubcmt.addItem(controlMilitar.getMilitarbyId(unidadeSelecionada.getIdsubcomandante()).getNome());
        btnExcluir.setVisible(true);
    }//GEN-LAST:event_tblUnidadesMouseClicked

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked

        btnExcluir.setVisible(false);
        limpaTodosCampos();

    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        Unidade unidade = new Unidade(txtNomeUnidade.getText(), Integer.parseInt(cmbMilCmt.getSelectedItem().toString()), Integer.parseInt(cmbMilSubcmt.getSelectedItem().toString()));
        try {
            unidadeDao.save(unidade);
            JOptionPane.showMessageDialog(null, "Unidade Salva com Sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar Unidade");
            throw e;
        }
        atualizaTabela();
        abaAlteraExclui.setSelectedIndex(0);

    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        unidadeDao.remove(unidadeSelecionada);
        atualizaTabela();
        btnExcluir.setVisible(false);
        abaAlteraExclui.setSelectedIndex(0);
    }//GEN-LAST:event_btnExcluirMouseClicked

    public void inicializa(ControlMilitarAdapter controlMilitar) {
        this.controlMilitar = controlMilitar;
    }

    private void limpaTodosCampos() {
        txtNomeUnidade.setText("");
        cmbPostogradCmt.setSelectedIndex(0);
        cmbPostogradSubcmt.setSelectedIndex(0);
        limpaCamposMilitar();
    }

    public void limpaCamposMilitar() {
        cmbMilCmt.removeAllItems();
        cmbMilSubcmt.removeAllItems();
    }

    public void atualizaTabela() {
        listaUnidade = unidadeDao.buscaUnidades();
        //remover itens exitentes nos campos da tela
        cmbPostogradCmt.removeAllItems();
        cmbPostogradSubcmt.removeAllItems();
        cmbMilCmt.removeAllItems();
        cmbMilSubcmt.removeAllItems();
        while (modeloTable.getRowCount() > 0) {
            modeloTable.removeRow(0);
        }

        //adiciona posto/graduacao nos campos
        cmbPostogradCmt.addItem(opcao);
        cmbPostogradSubcmt.addItem(opcao);
        for (SafoPostoGraducao pgaux : listaPG) {
            cmbPostogradCmt.addItem(pgaux.getAbreviacao());
            cmbPostogradSubcmt.addItem(pgaux.getAbreviacao());
        }

        for (Unidade unidadeaux : listaUnidade) {
            //adiciona unidades na tabela
            modeloTable.addRow(new Object[]{unidadeaux.getIdunidade(), unidadeaux.getNome(), unidadeaux.getIdcomandante(), unidadeaux.getIdsubcomandante()});
        }
    }
}
