\set AUTOCOMMIT OFF
BEGIN;

INSERT INTO "tipoviatura" (idtipoviatura,descricao) VALUES (1,' TRANSPORTE DE PESSOAS'),(2,' PLATAFORMA'),(3,' PLATAFORMA'),(4,' PLATAFORMA'),(5,' TRANSPORTE DE CARGA'),(6,' ADMINISTRATIVA'),(7,' QUADRICICULO');
INSERT INTO "tipoviatura" (idtipoviatura,descricao) VALUES (8,' INCENDIO FLORESTAL'),(9,' QUADRICICULO'),(10,' TRAILER'),(11,' TRANSPORTE DE PESSOAS'),(12,' TRANSPORTE DE PESSOAS'),(13,'ABS'),(14,' CAES');
INSERT INTO "tipoviatura" (idtipoviatura,descricao) VALUES (15,' ADMINISTRATIVA'),(16,' CHEFE DE OPERACOES CORTE DE ARVORES'),(17,' PRODUTOS PERIGOSOS'),(18,' INCENDIO FLORESTAL'),(19,' CAES'),(20,' ADMINISTRATIVA'),(21,' CEPDEC');

COMMIT;